### ISSUE TITLE
Missing Ground truth data

### ISSUE THREAD

**Issue by HEMA-MATHAVAN** [SAILResearch/replication-classifier_conf_config_bugloc#1]
The paper states that "We provide our ground truth dataset online [55]" , But i cant find the ground truth dataset or database in this github repository. kindly direct me, where i can find this particular dataset.

**Comment by golivax** [comment]
Dear @HEMA-MATHAVAN , thank you for your message. The ground truth data was indeed missing. I have just added it now (commit 97aafc57f111a3c3b26bbaf97d3e65360eb40d4c). Thanks!
