### ISSUE TITLE
Actual data

### ISSUE THREAD

**Issue by HEMA-MATHAVAN** [SAILResearch/replication-classifier_conf_config_bugloc#2]
Hi sail team,
 Can you people provide the actual bug reports and source code that was used in this particular research paper. The repository contains only ground truth table and results.

**Comment by golivax** [comment]
Hi Hema. We don't have the files anymore. However, in the bugs-to-files zip file (https://github.com/SAILResearch/replication-classifier_conf_config_bugloc/files/1738073/bugs-to-files.zip), you have a table with the bug ids and the associated file.  For instance, in the Eclipse bugs-to-file spreadsheet, the first row points to bug 7229. This bug can be found here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=7229. I suppose the file itself can be recovered from the version control system of the project or from its release history.
